version: '3.8'

services:
  mewallet-backend:
    build: .
    container_name: mewallet-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./wallet.db:/app/wallet.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
